/**
 * Created May 9, 2023
 */

#ifndef GFORMS_Error_H
#define GFORMS_Error_H

#pragma once

#define GFORMS_ERROR_HTTP_CODE_UNDEFINED -1000
#define GFORMS_ERROR_RANGE -100

/// TCP client errors
#define GFORMS_ERROR_TCP_ERROR_CONNECTION_REFUSED (-1)
#define GFORMS_ERROR_TCP_ERROR_SEND_REQUEST_FAILED (-2)
#define GFORMS_ERROR_TCP_ERROR_NOT_CONNECTED (-3)
#define GFORMS_ERROR_TCP_ERROR_CONNECTION_LOST (-4)
#define GFORMS_ERROR_TCP_ERROR_NO_STREAM (-5)
#define GFORMS_ERROR_TCP_ERROR_NO_HTTP_SERVER (-6)
#define GFORMS_ERROR_TCP_ERROR_TOO_LESS_RAM (-7)
#define GFORMS_ERROR_TCP_ERROR_ENCODING (-8)
#define GFORMS_ERROR_TCP_ERROR_STREAM_WRITE (-9)
#define GFORMS_ERROR_TCP_ERROR_CONNECTION_INUSED (-10)
#define GFORMS_ERROR_TCP_RESPONSE_PAYLOAD_READ_TIMED_OUT (-11)
#define GFORMS_ERROR_TCP_RESPONSE_READ_FAILED (-12)


/// HTTP codes see RFC7231
#define GFORMS_ERROR_HTTP_CODE_OK 200
#define GFORMS_ERROR_HTTP_CODE_NON_AUTHORITATIVE_INFORMATION 203
#define GFORMS_ERROR_HTTP_CODE_NO_CONTENT 204
#define GFORMS_ERROR_HTTP_CODE_MOVED_PERMANENTLY 301
#define GFORMS_ERROR_HTTP_CODE_FOUND 302
#define GFORMS_ERROR_HTTP_CODE_USE_PROXY 305
#define GFORMS_ERROR_HTTP_CODE_TEMPORARY_REDIRECT 307
#define GFORMS_ERROR_HTTP_CODE_PERMANENT_REDIRECT 308
#define GFORMS_ERROR_HTTP_CODE_BAD_REQUEST 400
#define GFORMS_ERROR_HTTP_CODE_UNAUTHORIZED 401
#define GFORMS_ERROR_HTTP_CODE_FORBIDDEN 403
#define GFORMS_ERROR_HTTP_CODE_NOT_FOUND 404
#define GFORMS_ERROR_HTTP_CODE_METHOD_NOT_ALLOWED 405
#define GFORMS_ERROR_HTTP_CODE_NOT_ACCEPTABLE 406
#define GFORMS_ERROR_HTTP_CODE_PROXY_AUTHENTICATION_REQUIRED 407
#define GFORMS_ERROR_HTTP_CODE_REQUEST_TIMEOUT 408
#define GFORMS_ERROR_HTTP_CODE_LENGTH_REQUIRED 411
#define GFORMS_ERROR_HTTP_CODE_PRECONDITION_FAILED 412
#define GFORMS_ERROR_HTTP_CODE_PAYLOAD_TOO_LARGE 413
#define GFORMS_ERROR_HTTP_CODE_URI_TOO_LONG 414
#define GFORMS_ERROR_HTTP_CODE_MISDIRECTED_REQUEST 421
#define GFORMS_ERROR_HTTP_CODE_UNPROCESSABLE_ENTITY 422
#define GFORMS_ERROR_HTTP_CODE_TOO_MANY_REQUESTS 429
#define GFORMS_ERROR_HTTP_CODE_REQUEST_HEADER_FIELDS_TOO_LARGE 431
#define GFORMS_ERROR_HTTP_CODE_INTERNAL_SERVER_ERROR 500
#define GFORMS_ERROR_HTTP_CODE_NOT_IMPLEMENTED 501
#define GFORMS_ERROR_HTTP_CODE_BAD_GATEWAY 502
#define GFORMS_ERROR_HTTP_CODE_SERVICE_UNAVAILABLE 503
#define GFORMS_ERROR_HTTP_CODE_GATEWAY_TIMEOUT 504
#define GFORMS_ERROR_HTTP_CODE_HTTP_VERSION_NOT_SUPPORTED 505
#define GFORMS_ERROR_HTTP_CODE_LOOP_DETECTED 508
#define GFORMS_ERROR_HTTP_CODE_NETWORK_AUTHENTICATION_REQUIRED 511

// GForms error
#define GFORMS_ERROR_BUFFER_OVERFLOW /*          */ (GFORMS_ERROR_RANGE - 1)
#define GFORMS_ERROR_DATA_TYPE_MISMATCH /*          */ (GFORMS_ERROR_RANGE - 2)
#define GFORMS_ERROR_PATH_NOT_EXIST /*          */ (GFORMS_ERROR_RANGE - 3)
#define GFORMS_ERROR_EXTERNAL_CLIENT_DISABLED /*          */ (GFORMS_ERROR_RANGE - 4)
#define GFORMS_ERROR_EXTERNAL_CLIENT_NOT_INITIALIZED /*          */ (GFORMS_ERROR_RANGE - 5)
#define GFORMS_ERROR_TOKEN_SET_TIME /*          */ (GFORMS_ERROR_RANGE - 6)
#define GFORMS_ERROR_TOKEN_CREATE_HASH /*          */ (GFORMS_ERROR_RANGE - 7)
#define GFORMS_ERROR_TOKEN_PARSE_PK /*          */ (GFORMS_ERROR_RANGE - 8)
#define GFORMS_ERROR_TOKEN_SIGN /*          */ (GFORMS_ERROR_RANGE - 9)
#define GFORMS_ERROR_TOKEN_EXCHANGE /*          */ (GFORMS_ERROR_RANGE - 10)
#define GFORMS_ERROR_TOKEN_NOT_READY /*          */ (GFORMS_ERROR_RANGE - 11)
#define GFORMS_ERROR_SYS_TIME_IS_NOT_READY /*          */ (GFORMS_ERROR_RANGE - 12)
#define GFORMS_ERROR_NTP_SYNC_TIMED_OUT /*          */ (GFORMS_ERROR_RANGE - 13)
#define GFORMS_ERROR_TOKEN_COMPLETE_NOTIFY /*          */ (GFORMS_ERROR_RANGE - 14)
#define GFORMS_ERROR_TOKEN_COMPLETE_UNNOTIFY /*          */ (GFORMS_ERROR_RANGE - 15)
#define GFORMS_ERROR_TOKEN_ERROR_UNNOTIFY /*          */ (GFORMS_ERROR_RANGE - 16)
#define GFORMS_ERROR_UDP_CLIENT_REQUIRED /*          */ (GFORMS_ERROR_RANGE - 17)
#define GFORMS_ERROR_MISSING_SERVICE_ACCOUNT_CREDENTIALS /*          */ (GFORMS_ERROR_RANGE - 18)
#define GFORMS_ERROR_SERVICE_ACCOUNT_JSON_FILE_PARSING_ERROR /*          */ (GFORMS_ERROR_RANGE - 19)
#endif